Gh-353: walletAddresses command
MASQ-Project/MASQ-Node-issues pull request #361
Opened 2021-01-05 18:43 UTC by bertllll

2021-01-16 14:42 UTC, bertllll commented on node/src/node_configurator/configurator.rs
> +                }
This is clumsy I am going to change line 197 to:  `payload: Err(error),` 

You cannot see it here but error in the match pattern is of a tuple of (u64, String).

2021-01-21 13:31 UTC, dnwiebe requested changes

2021-01-21 13:31 UTC, dnwiebe commented on USER-INTERFACE-INTERFACE.md
> +This message directs the Node to look for two pieces of information, the existing wallet addresses. For consuming wallet, it will be computed from the mnemonic seed and the stored derivation path (ch
It looks like the documentation for newPassword is duplicated. Also, this looks like part of the documentation for walletAddresses that got mixed in with one of the newPassword copies. Finally, the walletAddresses command should be in alphabetical order (at or near the bottom), so that someone who's scanning the documentation for it can find it easily.

2021-01-21 13:31 UTC, dnwiebe commented on USER-INTERFACE-INTERFACE.md
> +This message carries the pair of wallet addresses that were generated in the past.
The word "generated" in these paragraphs might be confusing, since the wallets might have been recovered rather than generated. You might be able to just remove the word "generated" entirely, at least in the second and third paragraphs.

2021-01-21 13:31 UTC, dnwiebe commented on masq/src/commands/generate_wallets_command.rs
> +        .about("Generates a pair of wallets (consuming and earning) for the Node if they haven't been generated already")
Good, but change the help for the recover-wallets command to match.

2021-01-21 13:31 UTC, dnwiebe commented on masq/src/commands/wallet_addresses.rs
> +        .about("Provides both addresses of created wallets. If no such wallets, generate-wallets command is where to start.")
Suggested rewording:
"Provides addresses of consuming and earning wallets. If no wallets exist, try generate-wallets or recover-wallets."
Maybe this can be improved too.

2021-01-21 13:31 UTC, dnwiebe commented on masq/src/commands/wallet_addresses.rs
> +    #[test]
The first two tests here should be moved to the CommandFactory.

2021-01-21 13:31 UTC, dnwiebe commented on masq/src/commands/wallet_addresses.rs
> +    fn wallet_addresses_command_with_no_password_wrong() {
Test name says "no password," but a password is being provided.

Also, there's nothing in this test that's unique to a complaint about a bad password. Any PayloadError on the back end would run exactly the same code that this test exercises. Therefore, a suggestion would be to name this test something about a payload error and make it a generalized test rather than specifically a bad-password test.

2021-01-21 13:31 UTC, dnwiebe commented on masq/src/commands/wallet_addresses.rs
> +        assert_eq!(
This assertion has already been made in at least one other test; to avoid duplicating code, you could remove it (and transact_params_arc, and the place where it's added to the mock) from here.

2021-01-21 13:31 UTC, dnwiebe commented on node/ci/run_integration_tests.sh
>  TOOLCHAIN_HOME="$1"
Remove this line too

2021-01-21 13:31 UTC, dnwiebe commented on node/src/node_configurator/configurator.rs
> +            let response = self.handle_wallet_addresses(body, context_id);
Add a debug! log about sending the response here, so that we can tell if the process wedges. Also, the first few clauses to this if statement should be changed the same way. (Sorry about being a bad example.)

2021-01-21 13:31 UTC, dnwiebe commented on node/src/node_configurator/configurator.rs
> -                    payload: Err((CONFIGURATOR_WRITE_ERROR, format!("{:?}", e))),
Good catch!

2021-01-21 13:31 UTC, dnwiebe commented on node/src/node_configurator/configurator.rs
> +            Err(error) => {
Instead of matching on Err(error), and then mentioning error.0 and error.1, match on Err((code, msg)) and then mention code and msg later. It's clearer.

2021-01-21 13:31 UTC, dnwiebe commented on node/src/node_configurator/configurator.rs
> +            Ok(addresses) => UiWalletAddressesResponse {
Instead of matching on Ok(addresses), and then mentioning addresses.0 and addresses.1, match on Ok((consuming, earning)) and then mention consuming and earning later. It's clearer.

2021-01-21 13:31 UTC, dnwiebe commented on node/src/node_configurator/configurator.rs
> +        if let Err(e) = self
Remove this password check; the password is checked by .mnemonic_seed() already.

2021-01-21 13:31 UTC, dnwiebe commented on node/src/node_configurator/configurator.rs
> +                None => panic!("Database corrupted!"),
Please be a little more specific about what's corrupted in the database--namely, that there's a mnemonic seed but no consuming-wallet derivation path. (Imagine getting this message ("Database corrupted!") from a tester and having to figure out what's wrong!)

2021-01-21 13:31 UTC, dnwiebe commented on node/src/node_configurator/configurator.rs
> +    fn generate_consuming_wallet(
The name for this function makes me assume that the wallet is being generated from scratch, the way it happens with the generate-wallet command. Maybe it could be reworded?

2021-01-21 13:31 UTC, dnwiebe commented on node/src/node_configurator/configurator.rs
> +            Ok(wallet) => wallet.expect("generateAddresses: earning_address: internal error"),
Two requests.

Primary: Can you make this error message mention both database corruption and the fact that we have a seed without an earning wallet?

Secondary: If this error construction looked more like the one above for a missing consuming wallet, the code would be faster to read.

2021-01-21 13:31 UTC, dnwiebe commented on node/src/node_configurator/configurator.rs
> +            .check_password_params(&check_password_params_arc)
If you get rid of the password check in the code, this will have to go with it.

2021-01-21 13:31 UTC, dnwiebe commented on node/src/node_configurator/configurator.rs
> +            .consuming_wallet_derivation_path_result(Ok(Some(String::from("m/44'/60'/0'/0/4"))))
Consider using the new derivation_path(0, 4) function here instead of a string; it's guaranteed to get the 44/60 thing right.

2021-01-21 13:31 UTC, dnwiebe commented on node/src/node_configurator/configurator.rs
> +                "snake, goal, cook, doom".as_bytes(),
Note: `"snake, goal, cook, doom".as_bytes()` is the same as `b"snake, goal, cook, doom"`.

2021-01-21 13:31 UTC, dnwiebe commented on node/src/node_configurator/configurator.rs
> +    fn handle_wallet_addresses_works_if_checking_password_fails() {
I think this test may go away when you remove the initial password check.

2021-01-21 13:31 UTC, dnwiebe commented on node/src/node_configurator/configurator.rs
> +            Err(e) => return Err((MNEMONIC_PHRASE_ERROR, format!("{:?}",e)))
This should be CONFIGURATOR_READ_ERROR for consistency with the other code.

2021-01-21 13:31 UTC, dnwiebe commented on node/src/node_configurator/configurator.rs
> +                None => return Err((CONFIGURATOR_READ_ERROR,"Wallets must exist prior to demanding info on them (recover or generate wallets first)".to_string())),
You could leave this here if you like, but it might be more illuminating if you created a new error code for this situation, since it is kind of a new condition that hasn't been encountered in the code before.

2021-01-21 13:31 UTC, dnwiebe commented on node/src/node_configurator/configurator.rs
> +                    DERIVATION_PATH_ERROR,
Running out of time: examine this and make sure it should be DERIVATION_PATH_ERROR and not CONFIGURATOR_READ_ERROR. Probably it should.

2021-01-21 13:31 UTC, dnwiebe commented on node/src/node_configurator/configurator.rs
> +            .consuming_wallet_derivation_path_result(Ok(Some(String::from("m/44'/60'/0'/0/4"))))
Consider using the new derivation_path() function

2021-01-21 13:31 UTC, dnwiebe commented on node/src/node_configurator/configurator.rs
> +                    EARNING_WALLET_ADDRESS_ERROR,
Again, this should probably be CONFIGURATOR_READ_ERROR.

2021-01-21 20:11 UTC, bertllll commented on node/src/node_configurator/configurator.rs
> +            Ok(wallet) => wallet.expect("generateAddresses: earning_address: internal error"),
I am not sure if I understand, if it can be called a corrupted database we probably want to start a panic...at least that's what we usually do. 
Maybe you want to be softer towards the user in this case like saying: "look man, database is corrupted I won't crash the app for you so that you can fix that; this one can be fixed as long as you try hard"

2021-01-21 20:49 UTC, bertllll commented on node/src/node_configurator/configurator.rs
> +            Ok(wallet) => wallet.expect("generateAddresses: earning_address: internal error"),
I'd rather leave only one format! macro there. I would be an unnecessary piece of code and I don't like it. 
If your note was about the plain "e" at one place and format!("{}",e) at the other one.

2021-01-22 12:03 UTC, dnwiebe commented on masq/src/commands/wallet_addresses.rs
> +    pub(crate) db_password: String,
pub instead of pub(crate)

2021-01-22 12:03 UTC, dnwiebe commented on node/src/node_configurator/configurator.rs
> +pub const EARLY_QESTIONING_ABOUT_DATA: u64 = CONFIGURATOR_PREFIX | 10;
EARLY_QUESTIONING_ABOUT_DATA

2021-01-22 12:03 UTC, dnwiebe commented on node/tests/node_exits_from_crash_message_test.rs
> +    println!("Before creating the directory"); ///////////////////////////////////////////////////////////////////////////////////////////
Remove println!()

2021-01-22 12:03 UTC, dnwiebe commented on port_exposer/ci/all.sh
>  TOOLCHAIN_HOME="$1"
Remove this line

2021-01-25 13:49 UTC, dnwiebe approved these changes

2021-01-25 13:50 UTC, merged